### ISSUE TITLE
Is it possible to create new NBT files?

### ISSUE THREAD

**Issue by wooky** [chmod222/cNBT#16]
I've looked through the header files, but I don't see any simple way to actually create a new NBT file and add branches to it. So is there a good way to do it?

**Comment by cgaebel** [comment]
I don't think such an API exists yet. Patches welcome!

**Comment by TheJavaProfessor** [comment]
Yes, no problem.
Msg me for help/info/support.

https://github.com/TheJavaProfessor/MCA-NBT-EDIT
https://github.com/TheJavaProfessor/MWC

**Comment by Low-power** [comment]
https://sourceforge.net/p/nbtfsutils/code/ci/nbtfsutils/tree/mkfs.nbt.c

It isn't too complicated to create an empty NBT file.

**Comment by wooky** [comment]
Closing due to age of issue.
